import type { AdminAccountTable } from './adminAccount.ts';
import type { CrisisTable } from './crisis.ts';
import type { EnrollmentTable } from './enrollment.ts';
import type { EnrollmentApplicationTable } from './enrollmentApplication.ts';
import type { EnrollmentApplicationDateTable } from './enrollmentApplicationDate.ts';
import type { EnrollmentDateTable } from './enrollmentDate.ts';
import type { OrganizationAccountTable } from './organizationAccount.ts';
import type { OrganizationCertificateInfoTable } from './organizationCertificateInfo.ts';
import type { OrganizationReportTable } from './organizationReport.ts';
import type { OrganizationRequestTable } from './organizationRequest.ts';
import type { PasswordResetTokenTable } from './passwordResetToken.ts';
import type { PlatformCertificateSettingsTable } from './platformCertificateSettings.ts';
import type { PostingTable } from './posting.ts';
import type { PostingSkillTable } from './postingSkill.ts';
import type { VolunteerAccountTable } from './volunteerAccount.ts';
import type { VolunteerPendingAccountTable } from './volunteerPendingAccount.ts';
import type { VolunteerReportTable } from './volunteerReport.ts';
import type { VolunteerSkillTable } from './volunteerSkill.ts';

export * from './adminAccount.ts';
export * from './crisis.ts';
export * from './enrollmentApplication.ts';
export * from './enrollmentApplicationDate.ts';
export * from './enrollmentDate.ts';
export * from './enrollment.ts';
export * from './organizationAccount.ts';
export * from './organizationCertificateInfo.ts';
export * from './posting.ts';
export * from './organizationReport.ts';
export * from './organizationRequest.ts';
export * from './passwordResetToken.ts';
export * from './postingSkill.ts';
export * from './volunteerAccount.ts';
export * from './volunteerPendingAccount.ts';
export * from './volunteerReport.ts';
export * from './platformCertificateSettings.ts';
export * from './volunteerSkill.ts';

export interface Database {
  volunteer_account: VolunteerAccountTable;
  volunteer_pending_account: VolunteerPendingAccountTable;
  organization_request: OrganizationRequestTable;
  organization_account: OrganizationAccountTable;
  admin_account: AdminAccountTable;
  crisis: CrisisTable;
  posting: PostingTable;
  posting_skill: PostingSkillTable;
  volunteer_skill: VolunteerSkillTable;
  password_reset_token: PasswordResetTokenTable;
  enrollment: EnrollmentTable;
  enrollment_application: EnrollmentApplicationTable;
  enrollment_application_date: EnrollmentApplicationDateTable;
  enrollment_date: EnrollmentDateTable;
  organization_report: OrganizationReportTable;
  volunteer_report: VolunteerReportTable;
  organization_certificate_info: OrganizationCertificateInfoTable;
  platform_certificate_settings: PlatformCertificateSettingsTable;
}
