name: Type check and Lint

on:
  push:
  pull_request:

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Type check and Lint
        working-directory: ./client
        run: npm run type:check && npm run lint:check

  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Type check and Lint
        working-directory: ./server
        run: npm run type:check && npm run lint:check
